export interface Task {
  id: string;
  taskId: string;
  title: string;
  department: string;
  assignee: string;
  assigneeInitials: string;
  priority: 'Critical' | 'High' | 'Medium' | 'Low';
  status: 'Draft' | 'Assigned' | 'Accepted' | 'In Progress' | 'Pending' | 'Blocked' | 'Under Review' | 'Changes Requested' | 'Approved' | 'Completed' | 'Closed' | 'Cancelled' | 'On Hold' | 'Reopened';
  dueDate: string;
  createdDate: string;
  progress: number;
  overdueDays: number;
  category: string;
  createdBy: string;
  description: string;
  reviewer: string;
  approver: string;
  tags: string[];
  subtaskCount: number;
  subtaskDone: number;
  commentCount: number;
  attachmentCount: number;
}

export const mockTasks: Task[] = [
  {
    id: 'task-001',
    taskId: 'FIN-2083-00431',
    title: 'Monthly Loan Disbursement Report — Ashwin 2083',
    department: 'Finance',
    assignee: 'Sita Rana',
    assigneeInitials: 'SR',
    priority: 'Critical',
    status: 'Under Review',
    dueDate: '2083-06-16',
    createdDate: '2083-06-10',
    progress: 90,
    overdueDays: 0,
    category: 'Financial Reporting',
    createdBy: 'Rajesh K. Shrestha',
    description: 'Prepare the comprehensive monthly loan disbursement report for Ashwin 2083, including total disbursements by category, branch-wise breakdown, and comparison with previous month.',
    reviewer: 'Narayan Paudel',
    approver: 'Rajesh K. Shrestha',
    tags: ['monthly', 'finance', 'loan'],
    subtaskCount: 4,
    subtaskDone: 3,
    commentCount: 7,
    attachmentCount: 2,
  },
  {
    id: 'task-002',
    taskId: 'CREDIT-2083-00315',
    title: 'Field Verification — Lalitpur Branch Loan Applications',
    department: 'Credit/Loan',
    assignee: 'Dipak Magar',
    assigneeInitials: 'DM',
    priority: 'High',
    status: 'In Progress',
    dueDate: '2083-06-20',
    createdDate: '2083-06-12',
    progress: 45,
    overdueDays: 0,
    category: 'Loan Processing',
    createdBy: 'Binod Karki',
    description: 'Conduct field verification visits for 8 pending loan applications from Lalitpur branch. Verify collateral, income sources, and residence.',
    reviewer: 'Binod Karki',
    approver: 'Narayan Paudel',
    tags: ['field-work', 'loan', 'verification'],
    subtaskCount: 8,
    subtaskDone: 3,
    commentCount: 3,
    attachmentCount: 5,
  },
  {
    id: 'task-003',
    taskId: 'ADM-2083-00118',
    title: 'Board Meeting Minutes — Ashwin 2083 Regular Meeting',
    department: 'Administration',
    assignee: 'Kamala Thapa',
    assigneeInitials: 'KT',
    priority: 'High',
    status: 'Assigned',
    dueDate: '2083-06-14',
    createdDate: '2083-06-09',
    progress: 0,
    overdueDays: 2,
    category: 'Board/Meeting',
    createdBy: 'Rajesh K. Shrestha',
    description: 'Prepare and circulate official minutes for the Ashwin 2083 regular board meeting held on 13 Ashwin. Include all resolutions, action items, and attendance record.',
    reviewer: 'Rajesh K. Shrestha',
    approver: 'Rajesh K. Shrestha',
    tags: ['board', 'minutes', 'urgent'],
    subtaskCount: 3,
    subtaskDone: 0,
    commentCount: 2,
    attachmentCount: 1,
  },
  {
    id: 'task-004',
    taskId: 'REC-2083-00067',
    title: 'Overdue Member Follow-up — Batch 9 (21 Members)',
    department: 'Recovery',
    assignee: 'Bikash Gurung',
    assigneeInitials: 'BG',
    priority: 'High',
    status: 'In Progress',
    dueDate: '2083-06-13',
    createdDate: '2083-06-06',
    progress: 35,
    overdueDays: 3,
    category: 'Recovery',
    createdBy: 'Narayan Paudel',
    description: 'Contact 21 members with overdue installments (30–90 days) in Batch 9. Document contact attempts, responses, and payment commitments.',
    reviewer: 'Narayan Paudel',
    approver: 'Narayan Paudel',
    tags: ['recovery', 'members', 'overdue'],
    subtaskCount: 21,
    subtaskDone: 7,
    commentCount: 4,
    attachmentCount: 0,
  },
  {
    id: 'task-005',
    taskId: 'HR-2083-00061',
    title: 'New Employee Onboarding — Priya Shrestha (Finance)',
    department: 'HR',
    assignee: 'Anita Shrestha',
    assigneeInitials: 'AS',
    priority: 'Medium',
    status: 'Accepted',
    dueDate: '2083-06-16',
    createdDate: '2083-06-13',
    progress: 25,
    overdueDays: 0,
    category: 'HR/Onboarding',
    createdBy: 'Anita Shrestha',
    description: 'Complete full onboarding for new Finance dept employee Priya Shrestha: ID creation, system access, orientation, policy acknowledgement, and department introduction.',
    reviewer: 'Anita Shrestha',
    approver: 'Rajesh K. Shrestha',
    tags: ['onboarding', 'hr', 'new-employee'],
    subtaskCount: 6,
    subtaskDone: 1,
    commentCount: 1,
    attachmentCount: 3,
  },
  {
    id: 'task-006',
    taskId: 'IT-2083-00089',
    title: 'Weekly Server Backup Verification — Week 38',
    department: 'IT',
    assignee: 'Suresh Pradhan',
    assigneeInitials: 'SP',
    priority: 'High',
    status: 'In Progress',
    dueDate: '2083-06-16',
    createdDate: '2083-06-15',
    progress: 40,
    overdueDays: 0,
    category: 'IT/Infrastructure',
    createdBy: 'Suresh Pradhan',
    description: 'Verify all scheduled backups completed successfully for week 38. Check backup integrity, storage capacity, and generate backup compliance report.',
    reviewer: 'Suresh Pradhan',
    approver: 'Rajesh K. Shrestha',
    tags: ['backup', 'it', 'weekly'],
    subtaskCount: 5,
    subtaskDone: 2,
    commentCount: 0,
    attachmentCount: 0,
  },
  {
    id: 'task-007',
    taskId: 'CREDIT-2083-00302',
    title: 'Credit Committee Loan Approval — Batch 12 (6 Applications)',
    department: 'Credit/Loan',
    assignee: 'Binod Karki',
    assigneeInitials: 'BK',
    priority: 'Critical',
    status: 'Pending',
    dueDate: '2083-06-17',
    createdDate: '2083-06-08',
    progress: 70,
    overdueDays: 0,
    category: 'Loan Processing',
    createdBy: 'Binod Karki',
    description: 'Prepare credit committee presentation for 6 loan applications in Batch 12. Include credit analysis, risk assessment, collateral valuation, and recommendation.',
    reviewer: 'Narayan Paudel',
    approver: 'Rajesh K. Shrestha',
    tags: ['credit-committee', 'loan', 'approval'],
    subtaskCount: 6,
    subtaskDone: 4,
    commentCount: 11,
    attachmentCount: 8,
  },
  {
    id: 'task-008',
    taskId: 'FIN-2083-00398',
    title: 'Q2 Financial Reconciliation Report — FY 2083/84',
    department: 'Finance',
    assignee: 'Sita Rana',
    assigneeInitials: 'SR',
    priority: 'Critical',
    status: 'Blocked',
    dueDate: '2083-06-11',
    createdDate: '2083-06-01',
    progress: 60,
    overdueDays: 5,
    category: 'Financial Reporting',
    createdBy: 'Rajesh K. Shrestha',
    description: 'Quarterly financial reconciliation blocked pending CBS system data export. Waiting for IT department to resolve CBS-2 data access issue.',
    reviewer: 'Narayan Paudel',
    approver: 'Rajesh K. Shrestha',
    tags: ['quarterly', 'finance', 'blocked', 'cbs'],
    subtaskCount: 7,
    subtaskDone: 4,
    commentCount: 9,
    attachmentCount: 3,
  },
  {
    id: 'task-009',
    taskId: 'MEM-2083-00041',
    title: 'Member KYC Update Drive — Expired Documents',
    department: 'Membership',
    assignee: 'Puja Tamang',
    assigneeInitials: 'PT',
    priority: 'Medium',
    status: 'In Progress',
    dueDate: '2083-06-30',
    createdDate: '2083-06-05',
    progress: 55,
    overdueDays: 0,
    category: 'Membership/KYC',
    createdBy: 'Puja Tamang',
    description: 'Contact 142 members with expired KYC documents for renewal. Collect updated citizenship copies, photos, and signatures. Update member database.',
    reviewer: 'Narayan Paudel',
    approver: 'Narayan Paudel',
    tags: ['kyc', 'members', 'compliance'],
    subtaskCount: 0,
    subtaskDone: 0,
    commentCount: 2,
    attachmentCount: 0,
  },
  {
    id: 'task-010',
    taskId: 'MKT-2083-00023',
    title: 'Dashain 2083 Member Communication Newsletter',
    department: 'Marketing',
    assignee: 'Puja Tamang',
    assigneeInitials: 'PT',
    priority: 'Low',
    status: 'Draft',
    dueDate: '2083-06-16',
    createdDate: '2083-06-14',
    progress: 0,
    overdueDays: 0,
    category: 'Marketing/Communication',
    createdBy: 'Puja Tamang',
    description: 'Design and send Dashain 2083 greetings newsletter to all 2,847 active members. Include cooperative updates, new products, and Dashain offers.',
    reviewer: 'Rajesh K. Shrestha',
    approver: 'Rajesh K. Shrestha',
    tags: ['newsletter', 'dashain', 'members'],
    subtaskCount: 3,
    subtaskDone: 0,
    commentCount: 0,
    attachmentCount: 0,
  },
  {
    id: 'task-011',
    taskId: 'ADM-2083-00125',
    title: 'Office Supply Procurement — Q2 Requisition',
    department: 'Administration',
    assignee: 'Kamala Thapa',
    assigneeInitials: 'KT',
    priority: 'Low',
    status: 'Approved',
    dueDate: '2083-06-20',
    createdDate: '2083-06-10',
    progress: 80,
    overdueDays: 0,
    category: 'Procurement',
    createdBy: 'Kamala Thapa',
    description: 'Process Q2 office supply procurement request. Collect quotations from 3 vendors, prepare comparative analysis, get approval, and place order.',
    reviewer: 'Narayan Paudel',
    approver: 'Rajesh K. Shrestha',
    tags: ['procurement', 'admin', 'supplies'],
    subtaskCount: 4,
    subtaskDone: 3,
    commentCount: 5,
    attachmentCount: 4,
  },
  {
    id: 'task-012',
    taskId: 'HR-2083-00044',
    title: 'Staff Performance Review Compilation — Q1 2083/84',
    department: 'HR',
    assignee: 'Anita Shrestha',
    assigneeInitials: 'AS',
    priority: 'High',
    status: 'Changes Requested',
    dueDate: '2083-06-15',
    createdDate: '2083-06-03',
    progress: 75,
    overdueDays: 1,
    category: 'HR/Performance',
    createdBy: 'Rajesh K. Shrestha',
    description: 'Compile Q1 performance reviews for all 43 staff members. Reviewer requested additional documentation for 5 staff members with below-average ratings.',
    reviewer: 'Rajesh K. Shrestha',
    approver: 'Rajesh K. Shrestha',
    tags: ['performance', 'hr', 'quarterly'],
    subtaskCount: 43,
    subtaskDone: 38,
    commentCount: 14,
    attachmentCount: 6,
  },
];